spring:

  datasource:
    url: jdbc:h2:tcp://localhost/~/NoBadDonation
    username: sa
    password:
    driver-class-name: org.h2.Driver

#run과 동시에 data.sql 실행
  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true

  security:
    oauth2:
      client:
        registration:
          google:
              client-id: 1016569789271-jgg8dcis0dvb9avb4n7jfo5nv43p4897.apps.googleusercontent.com
              client-secret: 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
              scope:
              - email
              - profile


#jwt:
#  header: Authorization
#  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
#  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
#  secret: c2lsdmVybmluZS10ZWNoLXNwcm
#  token-validity-in-seconds: 86400

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

