# Ethereum client
spring:
  web3j:
    client-addrss: 'http://127.0.0.1:8545'
    admin-client: true

# Ethereum accounts
eth:
  key:
    path: 'classpath:keystore/'
  gas:
    limit: '8000000'
    price: '0'
  contract:
    token: '0x9155408Dd7EEf3c07bB35cAED4763dEF83E329e9'
    member: '0x93d9d77106AA24bADd14D215EFBe08097Ba09De1'
  admin:
    wallet: 'admin.wallet'
    password: 'pass0'
    account: '0xfe30597e880ffc5d4b32b4a746be6facd4629ed2'